In [1]:
%matplotlib inline
%pylab inline

Populating the interactive namespace from numpy and matplotlib


# Data

In [2]:
X = [[93, 74],
     [94, 78],
     [96, 80], 
     [101, 84],
     [102, 85],
     [103, 81],
     [104, 83],
     [106, 83],
     [107, 82],
     [112, 89],
     [113, 88],
     [114, 86],
     [116, 90],
     [117, 90],
     [117, 91],
     [119, 93],
     [120, 89],
     [120, 93],
     [121, 95],
     [123, 93],
     [127, 96],
     [128, 95],
     [131, 95],
     [135, 106]]
     
Y = [[98, 81],
     [103, 84],
     [103, 86],
     [105, 86],
     [109, 88],
     [123, 92],
     [123, 95],
     [133, 99],
     [133, 102],
     [133, 102],
     [134, 100],
     [136, 102],
     [137, 98],
     [138, 99],
     [141, 103],
     [147, 108],
     [149, 107],
     [153, 107],
     [155, 115],
     [155, 117],
     [158, 115],
     [159, 118],
     [162, 124],
     [177, 132]]

X = np.asarray(X)
Y = np.asarray(Y)

In [3]:
print 'X shape:', X.shape
print 'Y shape:', Y.shape

X shape: (24, 2)
Y shape: (24, 2)


# Canonical Correlation Analysis

In [11]:
from __future__ import division

def cca(X, Y, inplace=False, verbose=False):
    
    # compute means
    print 'Computing means' if verbose else None
    mx = np.mean(X, axis=0)
    my = np.mean(Y, axis=0)
    
    # mean center views
    print 'Centering views' if verbose else None 
    X -= mx
    Y -= my
    
    # compute SVD of X
    print 'Computing SVD of X' if verbose else None 
    Ux, Sx, Vx = np.linalg.svd(X, full_matrices=False)
    
    # compute SVD of Y
    print 'Computing SVD of Y' if verbose else None 
    Uy, Sy, Vy = np.linalg.svd(Y, full_matrices=False)
    
    # compute cross-correlation in U-bases
    print 'Computing cross-correlation Cxy' if verbose else None 
    Cxy = Ux.T.dot(Uy)
    
    # compute SVD of Cxy
    print 'Computing SVD of Cxy' if verbose else None 
    Fx, C, Fy = np.linalg.svd(Cxy, full_matrices=False)
    
    print 'Computing CCA bases, Wx and Wy' if verbose else None 
    Wx = Vx.T.dot(1/Sx[..., None] * Fx) 
    Wy = Vy.T.dot(1/Sy[..., None] * Fy.T)
    
    return Wx, Wy, mx, my, C

In [12]:
Wx, Wy, mx, my, C = cca(X, Y,inplace=False, verbose=True)

Computing means
Centering views
Computing SVD of X
Computing SVD of Y
Computing cross-correlation Cxy
Computing SVD of Cxy
Computing CCA bases, Wx and Wy


In [6]:
print Wx.shape
print Wy.shape

print mx.shape
print my.shape

(2, 2)
(2, 2)
(2,)
(2,)


In [7]:
Zx = X.dot(Wx)
Zy = Y.dot(Wy)

In [8]:
Z = np.hstack((Zx, Zy))

In [9]:
print Z.shape

(24, 4)


In [10]:
print Z.T.dot(Z)
print Zx.T.dot(Zx)
print Zy.T.dot(Zy)
print Zx.T.dot(Zy)
print Zy.T.dot(Zx)

[[  1.00000000e+00   9.15933995e-16   9.77452923e-01   4.13558077e-15]
 [  9.15933995e-16   1.00000000e+00   8.32667268e-16   1.78899294e-01]
 [  9.77452923e-01   8.32667268e-16   1.00000000e+00   4.13558077e-15]
 [  4.13558077e-15   1.78899294e-01   4.13558077e-15   1.00000000e+00]]
[[  1.00000000e+00   9.15933995e-16]
 [  9.15933995e-16   1.00000000e+00]]
[[  1.00000000e+00   4.13558077e-15]
 [  4.13558077e-15   1.00000000e+00]]
[[  9.77452923e-01   4.13558077e-15]
 [  8.32667268e-16   1.78899294e-01]]
[[  9.77452923e-01   8.32667268e-16]
 [  4.13558077e-15   1.78899294e-01]]


In [13]:
C

array([ 0.97866164,  0.19605886])